baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'HYPEch, Learning by Doing'

google_analytics_id: "179125452"
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/hypech300_190.png"
  desktop: "images/logo/hypech150.png"
  desktop_height: "100px"
footer:
  copyright_text: 'HYPEch by <a class="zerostatic" href="https://hypech.com">hypech.com</a>'

seo:
  meta_og_title: "HYPEch Publisher"
  meta_og_type: "website"
  meta_og_url: "https://hypech.com"
  meta_og_image: "https://hypech.com/images/logo/aiHearing.png"
  meta_og_description: "Leaning by Doing Case Study."
  meta_twitter_card: "summary"
  meta_twitter_site: "@aihearing"
  meta_twitter_creator: "@aihearing"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
